version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python hello.py"
    environment:
      - DB_HOST=db
      - DB_NAME=messtracker
      - DB_USER=postgres
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=messtracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
